### ISSUE TITLE
Add wiremock module

### ISSUE THREAD

**Issue by MrAolen** [ekino/jcv#22]
Hi,

it could be cool to provide a wiremock module to validate request or response body json with JCV validators. 

In wiremock, when we try to compare a json array with another one but not in the same order, the `EqualToJsonPattern` doesn't match. ( here is an issue in wiremock repository : https://github.com/tomakehurst/wiremock/issues/1230 ). If we use a JCV with wiremock it should fix this.

If you want to test the current `EqualToJsonPattern` error, here is a test :

``` java
@Test
  void reproduceFailingIgnoreArrayOrder() {
    var expected = "{ \"array\": [\"a\",\"b\",\"c\",\"d\",\"e\",\"f\",\"g\",\"h\"] }";
    var actual = "{ \"array\": [\"b\",\"a\",\"d\",\"c\",\"e\",\"f\",\"g\",\"h\"] }";
    var pattern = new EqualToJsonPattern(expected, true, false);
    var result = pattern.match(actual);
    var exact = result.isExactMatch();
    assertTrue(exact);
  }
```

**Comment by clemstoquart** [comment]
Hi,

I cant' reproduce the failing test with both JDK 11.0.9 and 15.

**Comment by leomillon** [comment]
@clemstoquart me neither, but anyway, this could still be an interesting feature

**Comment by leomillon** [comment]
Erratum: it's failing with WireMock version `2.25.1` but not anymore with the latest `2.27.2` version
